"""Modules for quantization."""
from .base_quantized_op import QuantizedOp
from .post_training import PostTrainingAffineQuantization, PostTrainingQATImporter
from .quantized_module import QuantizedModule
from .quantized_ops import (
    QuantizedAbs,
    QuantizedAdd,
    QuantizedAvgPool,
    QuantizedBatchNormalization,
    QuantizedCelu,
    QuantizedClip,
    QuantizedConv,
    QuantizedDiv,
    QuantizedElu,
    QuantizedErf,
    QuantizedExp,
    QuantizedGemm,
    QuantizedGreater,
    QuantizedGreaterOrEqual,
    QuantizedHardSigmoid,
    QuantizedHardSwish,
    QuantizedIdentity,
    QuantizedLeakyRelu,
    QuantizedLess,
    QuantizedLessOrEqual,
    QuantizedLog,
    QuantizedMatMul,
    QuantizedMul,
    QuantizedOr,
    QuantizedPad,
    QuantizedPow,
    QuantizedPRelu,
    QuantizedReduceSum,
    QuantizedRelu,
    QuantizedReshape,
    QuantizedRound,
    QuantizedSelu,
    QuantizedSigmoid,
    QuantizedSoftplus,
    QuantizedSub,
    QuantizedTanh,
    QuantizedWhere,
)
from .quantizers import QuantizedArray
