run_example: run_sh load_to_cml

run_sh:
	@echo "Running federated learning training script..."
	@./run.sh

load_to_cml:
	@echo "Loading and compiling the model with Concrete ML..."
	@python load_to_cml.py
