FROM zamafhe/concrete-ml:v0.6.1
WORKDIR /project
COPY client.py .
COPY model.py .
COPY brevitas_utils.py .
COPY client_requirements.txt .
COPY 8_bit_model.pt .
RUN python -m pip install -r client_requirements.txt
RUN python -m pip install torchvision==0.13 --no-deps
ENTRYPOINT /bin/bash
