FROM zamafhe/concrete-ml
WORKDIR /project
COPY ./Tweets.csv ./Tweets.csv
COPY ./train_requirements.txt ./train_requirements.txt
RUN python -m pip install -r train_requirements.txt
COPY ./train.py ./train.py
COPY ./utils.py ./utils.py
ENTRYPOINT python train.py
