FROM zamafhe/concrete-ml
WORKDIR /project
COPY client.py .
COPY utils.py .
COPY client_requirements.txt .
COPY ./hf_cache ./hf_cache
RUN python -m pip install -r client_requirements.txt
ENTRYPOINT /bin/bash
