FROM zamafhe/concrete-ml:v1.8.0
WORKDIR /project

# Add a non-root user and group
RUN groupadd -g 10001 grp02 && \
    useradd -u 10000 -g grp02 usr01 && \
    chown -R usr01:grp02 /project

COPY client_requirements.txt .
RUN python -m pip install -r client_requirements.txt
COPY client.py .

# Switch to the non-root user
USER usr01:grp02

ENTRYPOINT /bin/bash
