FROM zamafhe/concrete-ml
WORKDIR /project
COPY requirements.txt  requirements.txt
#RUN python -m pip install torchvision==0.14.1 --no-deps
RUN python -m pip install -r requirements.txt
RUN python -m pip install requests

COPY models/ models/
COPY experiments/ experiments/
COPY compile.py compile.py

ENTRYPOINT python compile.py
