FROM zamafhe/concrete-ml
WORKDIR /project
COPY client.py .
COPY clear_module.py .
COPY constants.py .
COPY brevitas_utils.py .
COPY client_requirements.txt .
COPY clear_module.pt .
RUN python -m pip install -r client_requirements.txt
RUN python -m pip install torchvision==0.14 --no-deps
ENTRYPOINT /bin/bash
